name: Sync to Hugging Face Hub
on:
  push:
    branches: [netlify_test] 
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: 
            git filter-branch --force --index-filter \
            'git rm -r --cached --ignore-unmatch backend/ml_models/weights/' \
            HEAD
            git push --force https://idident:$HF_TOKEN@huggingface.co/spaces/idident/forgefind HEAD:main
