name: Sync to Hugging Face Hub
on:
  push:
    branches: [netlify_test] 
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Replace 'idident' with your HF username and 'forgefind' with your Space name
        run: git push --force https://idident:$HF_TOKEN@huggingface.co/spaces/idident/forgefind main